# Generated by Django 3.2 on 2021-06-22 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('idPelicula', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Pelicula')),
                ('nombrePelicula', models.CharField(max_length=50, verbose_name='Nombre de la Pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('correo', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Correo')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('comentario', models.CharField(max_length=150, verbose_name='Comentario')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelicula')),
            ],
        ),
    ]
