# Generated by Django 3.2 on 2021-07-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('pais', models.CharField(max_length=10, verbose_name='Pais')),
                ('contrasena', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
    ]
